# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  # aws cli orb
  aws-cli: circleci/aws-cli@4.0.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    description: Build and deploy the app
    docker:
      - image: cimg/node:18.16.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build app
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - "dist"
  create_s3_bucket:
    description: Create an S3 bucket
    executor: aws-cli/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile_name: circeci
      - run: aws cloudformation deploy \
          --template-file cloudformation/create-s3-bucket.yml --stack-name create-s3-bucket-${CIRCLE_WORKFLOW_ID:0:7} \
          --parameter-overrides BucketName=bucket-${CIRCLE_WORKFLOW_ID:0:7}
      - run: aws s3 sync dist/ s3://bucket-${CIRCLE_WORKFLOW_ID:0:7} --delete

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  deploy:
    jobs:
      - build
      - create_s3_bucket:
          requires:
            - build
