# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.2.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  create_infrastructure:
    description: Deploy the provision.yml CloudFormation template
    executor: aws-cli/default # the target machine image on which the job runs
    steps:
      - checkout
      - run:
          name: Create infrastructure
          command: |
            aws cloudformation deploy --template-file ./cloudformation/provision.yml --stack-name password-stack-${CIRCLE_BUILD_NUM}

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  deploy:
    jobs:
      - create_infrastructure
